name: Запуск бота по расписанию

on:
  schedule:
    - cron: '*/2 8-17 * * *'   # каждые 2 минуты с 8:00 до 17:58
  workflow_dispatch:            # можно запустить вручную

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install aiogram==3.17.0
      - run: python bot.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
